### ISSUE TITLE
Add option to toggle CSS queries

### ISSUE THREAD

**Issue by nandorojo** [intergalacticspacehighway/react-native-responsive-query#10]
I would be nice to declaratively enable and disable the CSS media queries. This way, we can test any differences there might be. And if someone isn’t using SSR, they might want it off.

We could add a `useCssMediaQueries` option(?)

**Comment by intergalacticspacehighway** [comment]
I don't think it would be that expensive, it uses a simple EventEmitter API, we can discuss it in a separate issue though. Created a PR with `disableCssMediaQueries` flag.

**Comment by intergalacticspacehighway** [comment]
Released in 0.2.0 🎉
